### ISSUE TITLE
Перевод 5 шуток из 2-го раздела

### ISSUE THREAD

**Issue by sdanilchenko** [devSchacht/Eat-the-World#2]
Готов взяться за перевод следующих пяти шуток (первые 5 из раздела 2, либо, если уже кто-то ими занимается - предложите следующие, которыми можно заняться).

Спасибо!

**Comment by maksugr** [comment]
Отлично!

Еще у самого раздела есть "карточка". Как в первом разделе цитата Маска. Возьметесь тоже создать необходимую обвязку для него и "карточку"? Только лучше бы это отдельным PR оформить, чтобы следующие можно было уже начинать, не дожидаясь пяти первых.

Я тогда беру 6-10 включительно)

Вам спасибо)

**Comment by sdanilchenko** [comment]
Да, конечно, сделаю отдельным PR карточку для второго раздела, думаю сразу и текст, и картинку, там вроде ничего неоднозначного нету:

# Раздел II. Объяснение шуток про работу программиста

> Программное обеспечение захватывает мир
>
> Марк Андрессен

---
ок?
